import type { Metadata } from "next";
import { Poppins, Jomhuria} from "next/font/google";
import "./globals.css";
import { ToastContainer } from 'react-toastify';

// Configure Poppins as the main font
const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-poppins',
});

// Configure Jomhuria for headings
const jomhuria = Jomhuria({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-jomhuria',
});


export const metadata: Metadata = {
  title: "SMS - Adventise International",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${jomhuria.variable} antialiased`}
      >
        {children}
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
      </body>
    </html>
  );
}
