import type { Metadata } from "next";
import localFont from "next/font/local"; // For Jomhuria fallback
import "./globals.css";

// Local fallback for Jomhuria
const jomhuria = localFont({
  src: [
    {
      path: '../resource/fonts/Jomhuria-Regular.ttf',
      weight: '400',
      style: 'normal',
    }
  ],
  variable: '--font-jomhuria',
});

// Local Poppins with all weights
const poppins = localFont({
  src: [
    {
      path: '../resource/fonts/Poppins-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../resource/fonts/Poppins-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../resource/fonts/Poppins-SemiBold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../resource/fonts/Poppins-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: "SMS - Adventise International",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable} ${jomhuria.variable}`}>
      <body className="font-sans antialiased">
        {children}
      </body>
    </html>
  );
}