import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import localFont from "next/font/local"; // For Jomhuria fallback
import "./globals.css";

// Configure Poppins as the main font
const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-poppins',
  display: 'swap',
});

// Local fallback for Jomhuria
const jomhuria = localFont({
  src: [
    {
      path: '../resource/fonts/Jomhuria-Regular.ttf',
      weight: '400',
      style: 'normal',
    }
  ],
  variable: '--font-jomhuria',
});

export const metadata: Metadata = {
  title: "SMS - Adventise International",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable} ${jomhuria.variable}`}>
      <body className="font-sans antialiased">
        {children}
      </body>
    </html>
  );
}